---
#cloud-config
users:
  - name: ${sshUserName}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: true
    ssh_authorized_keys:
      - ${sshPubKey}

packages:
  - podman
  - git
  - jq
  - vim

yum_repos:
  epel:
    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
    enabled: true
    gpgcheck: false
    name: Extra Packages for Enterprise Linux 7

write_files:
      - content: |
          # This file controls the state of SELinux on the system.
          # SELINUX= can take one of these three values:
          #     enforcing - SELinux security policy is enforced.
          #     permissive - SELinux prints warnings instead of enforcing.
          #     disabled - No SELinux policy is loaded.
          SELINUX=permissive
          # SELINUXTYPE= can take one of these three values:
          #     targeted - Targeted processes are protected,
          #     minimum - Modification of targeted policy. Only selected processes are protected.
          #     mls - Multi Level Security protection.
          SELINUXTYPE=targeted
        owner: root:root
        path: /etc/selinux/config
        permissions: '0644'


      - content: |
          [Unit]
          Description="HashiCorp Consul"
          Documentation=https://www.consul.io/
          Requires=network-online.target
          After=network-online.target

          [Service]
          Restart=on-failure
          Environment=CONSUL_DATA=/opt/consul
          Environment=IMAGE=docker.io/library/consul
          Environment=CONSUL_ETC=/etc/consul.d
          Environment=HOST_INT=127.0.0.1
          Environment=TAG=1.7.2
          ExecStartPre=/bin/mkdir -p ${CONSUL_DATA}
          ExecStartPre=/bin/mkdir -p ${CONSUL_ETC}
          ExecStartPre=/bin/chown -R 100:1000 ${CONSUL_DATA} ${CONSUL_ETC}
          ExecStartPre=/usr/bin/rm -f /%t/%n-pid /%t/%n-cid
          ExecStart=/usr/bin/podman run --conmon-pidfile /%t/%n-pid --cidfile /%t/%n-cid --log-driver=journald  –env-host=true --name consul -v ${CONSUL_DATA}:${CONSUL_DATA}  -p ${HOST_INT}:8500:8500 -p  ${HOST_INT}:8600:8600/udp  -d  ${IMAGE}:${TAG} agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -ui  -join 127.0.0.1 -data-dir=${CONSUL_DATA} -config-dir=${CONSUL_ETC}
          ExecStop=/usr/bin/sh -c "/usr/bin/podman rm -f `cat /%t/%n-cid`"
          KillMode=none
          Type=forking
          PIDFile=/%t/%n-pid

          [Install]
          WantedBy=multi-user.target
        owner: root:root
        path: /etc/systemd/system/consul.service
        permissions: '0644'

power_state:
#  delay: "+30"
  mode: reboot
  message: "We completed!! So, reboot.."
  timeout: 10
  condition: True