---
#cloud-config
users:
  - name: ${sshUserName}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: true
    ssh_authorized_keys:
      - ${sshPubKey}

packages:
  - podman
  - git
  - jq
  - vim
#curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
yum_repos:
  epel:
    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
    enabled: true
    gpgcheck: false
    name: Extra Packages for Enterprise Linux 7

  kubic:
      name: Stable Releases of Upstream github.com/containers packages (CentOS_7)
      baseurl: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
      gpgcheck: false
      enabled: 1

write_files:
      - content: |
          # This file controls the state of SELinux on the system.
          # SELINUX= can take one of these three values:
          #     enforcing - SELinux security policy is enforced.
          #     permissive - SELinux prints warnings instead of enforcing.
          #     disabled - No SELinux policy is loaded.
          SELINUX=permissive
          # SELINUXTYPE= can take one of these three values:
          #     targeted - Targeted processes are protected,
          #     minimum - Modification of targeted policy. Only selected processes are protected.
          #     mls - Multi Level Security protection.
          SELINUXTYPE=targeted
        owner: root:root
        path: /etc/selinux/config
        permissions: '0644'

      - encoding: b64
        content: W1VuaXRdCkRlc2NyaXB0aW9uPSJIYXNoaUNvcnAgQ29uc3VsIgpEb2N1bWVudGF0aW9uPWh0dHBzOi8vd3d3LmNvbnN1bC5pby8KUmVxdWlyZXM9bmV0d29yay1vbmxpbmUudGFyZ2V0CkFmdGVyPW5ldHdvcmstb25saW5lLnRhcmdldAoKW1NlcnZpY2VdClJlc3RhcnQ9b24tZmFpbHVyZQpFbnZpcm9ubWVudD1DT05TVUxfREFUQT0vb3B0L2NvbnN1bApFbnZpcm9ubWVudD1JTUFHRT1kb2NrZXIuaW8vbGlicmFyeS9jb25zdWwKRW52aXJvbm1lbnQ9Q09OU1VMX0VUQz0vZXRjL2NvbnN1bC5kCkVudmlyb25tZW50PUhPU1RfSU5UPTEyNy4wLjAuMQpFbnZpcm9ubWVudD1UQUc9MS43LjIKRXhlY1N0YXJ0UHJlPS9iaW4vbWtkaXIgLXAgJHtDT05TVUxfREFUQX0KRXhlY1N0YXJ0UHJlPS9iaW4vbWtkaXIgLXAgJHtDT05TVUxfRVRDfQpFeGVjU3RhcnRQcmU9L2Jpbi9jaG93biAtUiAxMDA6MTAwMCAke0NPTlNVTF9EQVRBfQpFeGVjU3RhcnRQcmU9L2Jpbi9jaG93biAtUiAxMDA6MTAwMCAke0NPTlNVTF9FVEN9CkV4ZWNTdGFydFByZT0vdXNyL2Jpbi9ybSAtZiAvJXQvJW4tcGlkIC8ldC8lbi1jaWQKRXhlY1N0YXJ0PS91c3IvYmluL3BvZG1hbiBydW4gLS1jb25tb24tcGlkZmlsZSAvJXQvJW4tcGlkIC0tY2lkZmlsZSAvJXQvJW4tY2lkIC0tbG9nLWRyaXZlcj1qb3VybmFsZCAtLWVudi1ob3N0PXRydWUgLS1uYW1lIGNvbnN1bCAtdiAke0NPTlNVTF9FVEN9OiR7Q09OU1VMX0VUQ30gLXYgJHtDT05TVUxfREFUQX06JHtDT05TVUxfREFUQX0gIC1wICR7SE9TVF9JTlR9Ojg1MDA6ODUwMCAtcCAgJHtIT1NUX0lOVH06ODYwMDo4NjAwL3VkcCAgLWQgICR7SU1BR0V9OiR7VEFHfSBhZ2VudCAtc2VydmVyIC11aSAtbm9kZT1zZXJ2ZXItMSAtYm9vdHN0cmFwLWV4cGVjdD0xIC1jbGllbnQ9MC4wLjAuMCAtdWkgIC1qb2luIDEyNy4wLjAuMSAtZGF0YS1kaXI9JHtDT05TVUxfREFUQX0gLWNvbmZpZy1kaXI9JHtDT05TVUxfRVRDfQpFeGVjU3RvcD0vdXNyL2Jpbi9zaCAtYyAiL3Vzci9iaW4vcG9kbWFuIHJtIC1mIGBjYXQgLyV0LyVuLWNpZGAiCktpbGxNb2RlPW5vbmUKVHlwZT1mb3JraW5nClBJREZpbGU9LyV0LyVuLXBpZAoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0
        owner: root:root
        path: /etc/systemd/system/consul.service
        permissions: '0644'

power_state:
#  delay: "+30"
  mode: reboot
  message: "We completed!! So, reboot.."
  timeout: 10
  condition: True